version: "3.9"
services:
  resource-service:
    build:
      context: ./resource-service
      dockerfile: ./Dockerfile
    ports:
      - "${RESOURCE_SERVICE_PORT}:${RESOURCE_SERVICE_PORT}"
    environment:
      RABBITMQ_HOST: rabbitmq
      DB_HOST: postgresqldb
      S3_HOST: ninja
      S3_PORT: 9000
      EUREKA_ZONE: http://eureka:8761/eureka
      API_GATEWAY: api-gateway
    depends_on:
      - resource-processor
      - rabbitmq
      - postgresqldb
      - ninja
      - eureka
  song-service:
    build:
      context: ./song-service
      dockerfile: ./Dockerfile
    ports:
      - "${SONG_SERVICE_PORT}:${SONG_SERVICE_PORT}"
    environment:
      DB_HOST: postgresqldb
      EUREKA_ZONE: http://eureka:8761/eureka
    depends_on:
      - postgresqldb
      - eureka
  resource-processor:
    build:
      context: ./resource-processor
      dockerfile: ./Dockerfile
    environment:
      RABBITMQ_HOST: rabbitmq
      EUREKA_ZONE: http://eureka:8761/eureka
    depends_on:
      - song-service
      - rabbitmq
      - api-gateway
  postgresqldb:
    image: postgres
    build:
      context: ./
      dockerfile: Dockerfile.postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
  ninja:
    image: scireum/s3-ninja
    ports:
      - "9444:9000"
    tmpfs:
      - "/home/sirius/data/${BUCKET_NAME}/:uid=2000,gid=2000"
  eureka:
    build:
      context: ./eureka-server/.
      dockerfile: ./Dockerfile
    ports:
      - "8761:8761"
  api-gateway:
    build:
      context: ./api-gateway/.
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    environment:
      EUREKA_ZONE: http://eureka:8761/eureka
    depends_on:
      - eureka