server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_ZONE:http://localhost:8761/eureka/}
  instance:
    appname: api-gateway
    preferIpAddress: true

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: resourceModule
          uri: lb://RESOURCE-SERVICE
          predicates:
            - Path=/resources/**
        - id: songModule
          uri: lb://SONG-SERVICE
          predicates:
            - Path=/songs/**