spring:
  application:
    name: resource-processor
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  codec:
    max-in-memory-size: 100MB
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    password: guest
    port: 15672
    username: guest
    exchange: resource.exchange
    queue: resource.queue
    routing-key: resource.routingkey
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 2
          max-interval: 100

retry:
  maxAttempts: 2
  maxDelay: 100

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_ZONE:http://localhost:8761/eureka/}
  instance:
    appname: resource-processor
    preferIpAddress: true

management:
  metrics:
    export:
      elastic:
        host: ${ELASTIC:http://localhost:9200}
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false