server:
  port: 8083

security:
  oauth2:
    resource:
      user-info-uri: ${AUTH_SERVER:http://localhost:8085/api/auth/user}

spring:
  application:
    name: storage-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost:5432}/storage
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

spring.jpa:
  database: POSTGRESQL
  hibernate.ddl-auto: update
  show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_ZONE:http://localhost:8761/eureka/}
  instance:
    appname: storage-serivice
    preferIpAddress: true